export const historyData = [
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "West",
        "gpsstatus": "Valid",
        "latitude": "18.7948",
        "longitude": "73.28978",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 06:58:34 AM",
        "vehiclespeed": "88.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "305.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Inside",
        "nhid": "0",
        "nhname": "NH548A"
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North West",
        "gpsstatus": "Valid",
        "latitude": "18.800606",
        "longitude": "73.285896",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 06:59:14 AM",
        "vehiclespeed": "19.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "328.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North West",
        "gpsstatus": "Valid",
        "latitude": "18.804014",
        "longitude": "73.283173",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 06:59:54 AM",
        "vehiclespeed": "47.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "329.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Stop",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North West",
        "gpsstatus": "Valid",
        "latitude": "18.807486",
        "longitude": "73.281097",
        "ignitionstatus": "OFF",
        "pollingdatetime": "28-Jan-2025 07:00:51 AM",
        "vehiclespeed": "0.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "330.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Stop",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North West",
        "gpsstatus": "Valid",
        "latitude": "18.807486",
        "longitude": "73.281097",
        "ignitionstatus": "OFF",
        "pollingdatetime": "28-Jan-2025 07:01:14 AM",
        "vehiclespeed": "0.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "330.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Stop",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North West",
        "gpsstatus": "Valid",
        "latitude": "18.807486",
        "longitude": "73.281097",
        "ignitionstatus": "OFF",
        "pollingdatetime": "28-Jan-2025 07:03:14 AM",
        "vehiclespeed": "0.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "330.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "West",
        "gpsstatus": "Valid",
        "latitude": "18.81452",
        "longitude": "73.276184",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:04:34 AM",
        "vehiclespeed": "83.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "307.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "West",
        "gpsstatus": "Valid",
        "latitude": "18.816883",
        "longitude": "73.272629",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:04:54 AM",
        "vehiclespeed": "80.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "305.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North West",
        "gpsstatus": "Valid",
        "latitude": "18.825735",
        "longitude": "73.26329",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:05:54 AM",
        "vehiclespeed": "100.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "323.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "West",
        "gpsstatus": "Valid",
        "latitude": "18.832453",
        "longitude": "73.250938",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:06:54 AM",
        "vehiclespeed": "91.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "307.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "West",
        "gpsstatus": "Valid",
        "latitude": "18.835291",
        "longitude": "73.247124",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:07:14 AM",
        "vehiclespeed": "90.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "308.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "West",
        "gpsstatus": "Valid",
        "latitude": "18.837862",
        "longitude": "73.243668",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:07:34 AM",
        "vehiclespeed": "74.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "308.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Idle",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North",
        "gpsstatus": "Valid",
        "latitude": "18.843685",
        "longitude": "73.235809",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:08:34 AM",
        "vehiclespeed": "0.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "0.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Idle",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North",
        "gpsstatus": "Valid",
        "latitude": "18.843685",
        "longitude": "73.235809",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:08:54 AM",
        "vehiclespeed": "0.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "0.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North West",
        "gpsstatus": "Valid",
        "latitude": "18.888704",
        "longitude": "73.207367",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:12:14 AM",
        "vehiclespeed": "80.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "331.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North West",
        "gpsstatus": "Valid",
        "latitude": "18.900127",
        "longitude": "73.201546",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:13:14 AM",
        "vehiclespeed": "87.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "316.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "West",
        "gpsstatus": "Valid",
        "latitude": "18.904646",
        "longitude": "73.193718",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:13:54 AM",
        "vehiclespeed": "87.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "299.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Idle",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North",
        "gpsstatus": "Valid",
        "latitude": "18.914518",
        "longitude": "73.177414",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:15:34 AM",
        "vehiclespeed": "0.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "0.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Idle",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North",
        "gpsstatus": "Valid",
        "latitude": "18.914518",
        "longitude": "73.177414",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:16:14 AM",
        "vehiclespeed": "0.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "0.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North West",
        "gpsstatus": "Valid",
        "latitude": "18.928967",
        "longitude": "73.162758",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:16:54 AM",
        "vehiclespeed": "100.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "316.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North West",
        "gpsstatus": "Valid",
        "latitude": "18.932802",
        "longitude": "73.159767",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:17:14 AM",
        "vehiclespeed": "90.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "332.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North West",
        "gpsstatus": "Valid",
        "latitude": "18.941191",
        "longitude": "73.157043",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:17:54 AM",
        "vehiclespeed": "88.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "345.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North West",
        "gpsstatus": "Valid",
        "latitude": "18.949905",
        "longitude": "73.15464",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:18:34 AM",
        "vehiclespeed": "88.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "351.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Outside",
        "nhid": "0",
        "nhname": ""
    },
    {
        "vehicleid": "JwvtgAvXdx95jB63QgV5DA==",
        "vehicleno": "MA3BNC62SRG845879",
        "vehicleclass": "Bus / Truck",
        "deviceimeino": "860560067088486",
        "deviceuniqueno": "BSTP17A082400023981",
        "pollingstatus": "Running",
        "customername": "",
        "customermobileno": "",
        "vehicledirectionname": "North",
        "gpsstatus": "Valid",
        "latitude": "18.958317",
        "longitude": "73.156937",
        "ignitionstatus": "ON",
        "pollingdatetime": "28-Jan-2025 07:19:14 AM",
        "vehiclespeed": "92.0",
        "fasttageno": "",
        "tripno": "NA",
        "stretchname": "NA",
        "vehicledirectionvalue": "19.0",
        "tripstatus": "NA",
        "onhiwaystatus": "Inside",
        "nhid": "0",
        "nhname": "NH48"
    }
]